name: BattleNPC
version: '${version}'

main: nl.grapjeje.battleNPC.Main
api-version: '1.21.11'
load: POSTWORLD

authors: [ GrapJeje ]
website: https://grapjeje.nl/

commands:
  battlenpc:
    description: Main plugin command /battlenpc to spawn the boss